version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: itaca_api
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../artifacts:/app/artifacts
      - ../scripts:/app/scripts
    restart: always

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: itaca_frontend
    ports:
      - "80:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
    depends_on:
      - api
    restart: always
